//
export const PERK_DATA = {
    BARBARIAN: {
        AXE_SPECIALIZATION: "DesignDataPerk:Id_Perk_AxeSpecialization",
        BERSERKER: "DesignDataPerk:Id_Perk_Berserker",
        CARNAGE: "DesignDataPerk:Id_Perk_Carnage",
        IRON_WILL: "DesignDataPerk:Id_Perk_IronWill",
        MORALE_BOOST: "DesignDataPerk:Id_Perk_MoraleBoost",
        SAVAGE: "DesignDataPerk:Id_Perk_Savage",
        CRUSH: "DesignDataPerk:Id_Perk_Crush",
        ROBUST: "DesignDataPerk:Id_Perk_Robust",
        TWO_HANDER: "DesignDataPerk:Id_Perk_TwoHander",
        POTION_CHUGGER: "DesignDataPerk:Id_Perk_PotionChugger",
        EXECUTIONER: "DesignDataPerk:Id_Perk_Executioner",
    },

    BARD: {
        LORE_MASTERY: "DesignDataPerk:Id_Perk_LoreMastery",
        MELODIC_PROTECTION: "DesignDataPerk:Id_Perk_MelodicProtection",
        RAPIER_MASTERY: "DesignDataPerk:Id_Perk_RapierMastery",
        WANDERERS_LUCK: "DesignDataPerk:Id_Perk_WanderersLuck",
        WAR_SONG: "DesignDataPerk:Id_Perk_WarSong",
    },

    CLERIC: {
        ADVANCED_HEALER: "DesignDataPerk:Id_Perk_AdvancedHealer",
        BLUNT_WEAPON_MASTERY: "DesignDataPerk:Id_Perk_BluntWeaponMastery",
        BREWMASTER: "DesignDataPerk:Id_Perk_Brewmaster",
        KINDNESS: "DesignDataPerk:Id_Perk_Kindness",
        PERSEVERANCE: "DesignDataPerk:Id_Perk_Perseverance",
        PROTECTIONFROM_EVIL: "DesignDataPerk:Id_Perk_ProtectionfromEvil",
        REQUIEM: "DesignDataPerk:Id_Perk_Requiem",
        UNDEAD_SLAYING: "DesignDataPerk:Id_Perk_UndeadSlaying",
        HOLY_AURA: "DesignDataPerk:Id_Perk_HolyAura",
    },

    FIGHTER: {
        BARRICADE: "DesignDataPerk:Id_Perk_Barricade",
        COMBO_ATTACK: "DesignDataPerk:Id_Perk_ComboAttack",
        COUNTERATTACK: "DesignDataPerk:Id_Perk_Counterattack",
        DEFENSE_EXPERT: "DesignDataPerk:Id_Perk_DefenseExpert",
        DUAL_WIELD: "DesignDataPerk:Id_Perk_DualWield",
        PROJECTILE_RESISTANCE: "DesignDataPerk:Id_Perk_ProjectileResistance",
        SHIELD_EXPERT: "DesignDataPerk:Id_Perk_ShieldExpert",
        SWIFT: "DesignDataPerk:Id_Perk_Swift",
        WEAPON_MASTERY: "DesignDataPerk:Id_Perk_WeaponMastery",
        ADRENALINE_SPIKE: "DesignDataPerk:Id_Perk_AdrenalineSpike",
        SLAYER: "DesignDataPerk:Id_Perk_Slayer",
    },

    RANGER: {
        CROSSBOW_MASTERY: "DesignDataPerk:Id_Perk_CrossbowMastery",
        ENHANCED_HEARING: "DesignDataPerk:Id_Perk_EnhancedHearing",
        KINESTHESIA: "DesignDataPerk:Id_Perk_Kinesthesia",
        NIMBLE_HANDS: "DesignDataPerk:Id_Perk_NimbleHands",
        RANGED_WEAPONS_EXPERT: "DesignDataPerk:Id_Perk_RangedWeaponsExpert",
        SHARPSHOOTER: "DesignDataPerk:Id_Perk_Sharpshooter",
        SPEAR_PROFICIENCY: "DesignDataPerk:Id_Perk_SpearProficiency",
        TRACKING: "DesignDataPerk:Id_Perk_Tracking",
        TRAP_EXPERT: "DesignDataPerk:Id_Perk_TrapExpert",
        CRIPPLING_SHOT: "DesignDataPerk:Id_Perk_CripplingShot",
        QUICK_RELOAD: "DesignDataPerk:Id_Perk_QuickReload",
    },

    ROGUE: {
        AMBUSH: "DesignDataPerk:Id_Perk_Ambush",
        BACK_ATTACK: "DesignDataPerk:Id_Perk_BackAttack",
        CREEP: "DesignDataPerk:Id_Perk_Creep",
        DAGGER_EXPERT: "DesignDataPerk:Id_Perk_DaggerExpert",
        HIDDEN_POCKET: "DesignDataPerk:Id_Perk_HiddenPocket",
        LOCKPICK_SET: "DesignDataPerk:Id_Perk_LockpickSet",
        PICKPOCKET: "DesignDataPerk:Id_Perk_Pickpocket",
        POISONED_WEAPON: "DesignDataPerk:Id_Perk_PoisonedWeapon",
        STEALTH: "DesignDataPerk:Id_Perk_Stealth",
        TRAP_DETECTION: "DesignDataPerk:Id_Perk_TrapDetection",
        DOUBLE_JUMP: "DesignDataPerk:Id_Perk_DoubleJump",
        JOKESTER: "DesignDataPerk:Id_Perk_Jokester",
        SHADOW_RUNNER: "DesignDataPerk:Id_Perk_ShadowRunner",
        THRUST: "DesignDataPerk:Id_Perk_Thrust",
    },

    WIZARD: {
        ARCANE_FEEDBACK: "DesignDataPerk:Id_Perk_ArcaneFeedback",
        ARCANE_MASTERY: "DesignDataPerk:Id_Perk_ArcaneMastery",
        FIRE_MASTERY: "DesignDataPerk:Id_Perk_FireMastery",
        ICE_SHIELD: "DesignDataPerk:Id_Perk_IceShield",
        MANA_SURGE: "DesignDataPerk:Id_Perk_ManaSurge",
        MELT: "DesignDataPerk:Id_Perk_Melt",
        QUICK_CHANT: "DesignDataPerk:Id_Perk_QuickChant",
        REACTIVE_SHIELD: "DesignDataPerk:Id_Perk_ReactiveShield",
        SAGE: "DesignDataPerk:Id_Perk_Sage",
    },
};
